server {
    listen 80;
    server_name longvacation.eu;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name longvacation.eu;

    ssl_certificate /etc/nginx/ssl/longvacation.eu.pem;
    ssl_certificate_key /etc/nginx/ssl/longvacation.eu.key;

    include /etc/nginx/includes/default.conf;
}

# Redirect HTTP
server {
    listen 80;
    server_name optimize-vacation-for.me www.optimize-vacation-for.me;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://longvacation.eu$request_uri;
    }
}

# Redirect HTTPS
server {
    listen 443 ssl;
    server_name optimize-vacation-for.me www.optimize-vacation-for.me;

    ssl_certificate /etc/nginx/ssl/longvacation.eu.pem;
    ssl_certificate_key /etc/nginx/ssl/longvacation.eu.key;

    return 301 https://longvacation.eu$request_uri;
}