// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VacationOptimizer.Server.Data;

#nullable disable

namespace VacationOptimizer.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314105547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VacationOptimizer.Server.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoCode = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 2,
                            IsoCode = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 3,
                            IsoCode = "US",
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("VacationOptimizer.Server.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 1, 1),
                            Name = "New Year's Day",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 1, 1),
                            Name = "New Year's Day",
                            StateId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 1, 1),
                            Name = "New Year's Day",
                            StateId = 3
                        });
                });

            modelBuilder.Entity("VacationOptimizer.Server.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Name = "Bavaria"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            Name = "California"
                        });
                });

            modelBuilder.Entity("VacationOptimizer.Server.Models.Holiday", b =>
                {
                    b.HasOne("VacationOptimizer.Server.Models.State", "State")
                        .WithMany("Holidays")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("VacationOptimizer.Server.Models.State", b =>
                {
                    b.HasOne("VacationOptimizer.Server.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("VacationOptimizer.Server.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("VacationOptimizer.Server.Models.State", b =>
                {
                    b.Navigation("Holidays");
                });
#pragma warning restore 612, 618
        }
    }
}
