import worldDots from "./content/world-dots.json";

// ── Dot dataset (generated by scripts/generate-globe-dots.mjs) ──

export const GLOBE_DOTS = worldDots.dots as [number, number][];

// ── Flat equirectangular projection ──
// Latitude is cropped to the inhabited band; Antarctica and the empty
// arctic cap are excluded (matches the generator's crop).

export const LAT_MAX = 84;
export const LAT_MIN = -56;
export const MAP_WIDTH = 1000;
export const MAP_HEIGHT = Math.round((MAP_WIDTH * (LAT_MAX - LAT_MIN)) / 360);

export function projectPoint(lngLat: [number, number]): { x: number; y: number } {
    return {
        x: ((lngLat[0] + 180) / 360) * MAP_WIDTH,
        y: ((LAT_MAX - lngLat[1]) / (LAT_MAX - LAT_MIN)) * MAP_HEIGHT,
    };
}

// ── Country marker coordinates ([lng, lat]) ──
// Intentionally a superset: markers are only rendered for codes returned by
// /api/vacations/countries, so unsupported countries can never appear even
// if listed here. Extend this map together with backend seed data.

export const COUNTRY_COORDS: Record<string, [number, number]> = {
    AT: [14.5, 47.6],
    AU: [134.0, -25.7],
    BE: [4.6, 50.6],
    BR: [-51.9, -12.3],
    CA: [-101.0, 56.1],
    CH: [8.2, 46.8],
    CO: [-74.3, 4.1],
    CZ: [15.4, 49.8],
    DE: [10.4, 51.2],
    DK: [9.4, 56.0],
    EC: [-78.5, -1.4],
    EE: [25.7, 58.7],
    ES: [-3.7, 40.3],
    FI: [26.0, 64.5],
    FR: [2.5, 46.6],
    GB: [-1.6, 54.4],
    GR: [22.5, 39.3],
    HR: [16.4, 45.6],
    HU: [19.4, 47.2],
    ID: [118.0, -2.2],
    IE: [-8.1, 53.2],
    IN: [79.0, 21.8],
    IT: [12.1, 42.9],
    JP: [138.5, 36.6],
    KZ: [67.3, 48.2],
    LT: [23.9, 55.3],
    LU: [6.1, 49.8],
    LV: [24.9, 56.9],
    ME: [19.3, 42.8],
    MX: [-102.5, 23.9],
    NL: [5.6, 52.2],
    NO: [11.5, 61.5],
    NZ: [172.8, -41.5],
    PL: [19.3, 52.1],
    PT: [-8.2, 39.6],
    RO: [25.0, 45.9],
    SE: [16.3, 62.2],
    SI: [14.8, 46.1],
    SK: [19.5, 48.7],
    TR: [35.2, 39.0],
    US: [-98.6, 39.8],
    ZA: [24.7, -29.0],
};

// Filters a list of ISO country codes down to those that both the backend
// supports and we have coordinates for. This is what keeps unsupported
// countries (e.g. HU, RO) off the map.
export function filterSupportedMarkers(codes: string[]): string[] {
    return codes
        .map((code) => code.toUpperCase())
        .filter((code) => Boolean(COUNTRY_COORDS[code]));
}
